version: '3'

services:
  app:
    container_name: app
    network_mode: "host"
    # image: ksobitov/node_pg:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=localhost
      - DB_USER=komil
      - DB_NAME=komil
      - DB_PASSWORD=password
      - DB_PORT=5433
